version: "3.3"

services:
  app:
    build: .
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mongodb://db:27017/grocery
      SERVER_URL: http://localhost:3000
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
