version: "3.3"

services:
  db:
    image: mongo
    container_name: db
    restart: always
    # command: mongod --bind_ip_all --replSet mongo-set
    ports:
      - 27017:27017
    networks:
      - store-app

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   command: server /data --console-address ":9001"
  #   networks:
  #     - store-app

  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
      - "7001:9001"
    volumes:
      - ./stacks:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  # auto_update:
  #   image: containrrr/watchtower:latest-dev
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --schedule "0 0 * ? * *" --label-enable --cleanup
  #   restart: unless-stopped

networks:
  store-app:
    driver: bridge
