version: "3.3"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 443:443
      - 80:80

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot --agree-tos --renew-by-default \
      --preferred-challenges http-01 --server https://acme-v02.api.letsencrypt.org/directory \
      --text --email quochuydev1@gmail.com \
      -w /tmp/letsencrypt -d cafeman.xyz

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: ".env"
    environment:
      DATABASE_URL: mongodb://db:27017/grocery

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
