version: "3.3"

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - service
    env_file: ".env"
    environment:
      DATABASE_URL: mongodb://db:27017/grocery
      SERVER_FILE_URL: http://localhost:4000

  service:
    image: quochuydev/services
    container_name: service
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      # Custom: grocery folder
      - /home/grocery/keys:/usr/src/app/keys
    environment:
      DATABASE_URL: mongodb://db:27017/service
      SERVER_URL: http://localhost:4000
      GCS_BUCKET: cafeman_files
      GCLOUD_PROJECT: coffee
      GCS_KEYFILE: ./keys/gcs_service_account.json

  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - 27017:27017
