version: "3.3"

services:
  nginx:
    restart: always
    name: nginx
    build:
      context: ./nginx
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    ports:
      - 443:443
      - 80:80

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: ".env"
    environment:
      DATABASE_URL: mongodb://db:27017/grocery

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
