version: "3.3"

services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      # custom
      - /home/admin-dashboard-store/build:/build
      # base
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    ports:
      - 443:443
      - 80:80

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: ".env"
    environment:
      DATABASE_URL: mongodb://db:27017/grocery

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
