version: "3.3"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 443:443
      - 80:80

  certbot:
    image: certbot/certbot
    container_name: certbot
    command: certonly --email quochuydev1@gmail.com --agree-tos --no-eff-email --staging -d cafeman.xyz  -d www.cafeman.xyz

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: ".env"
    environment:
      DATABASE_URL: mongodb://db:27017/grocery

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
