version: "3.3"

services:
  db:
    image: mongo
    container_name: db
    restart: always
    # command: mongod --bind_ip_all --replSet mongo-set
    ports:
      - 27017:27017
    networks:
      - store-app

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    networks:
      - store-app

networks:
  store-app:
    driver: bridge