name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: touch .env
      - run: echo DATABASE_URL=mongodb://localhost:27017/grocery >> .env
      - run: docker-compose up -d
      - run: yarn
      - run: yarn build
      - run: yarn start
